/// <reference types="pdfkit" />
import { Doc } from '../../types';
export declare namespace GuiaSPSADTOpts {
    const pdfOptions: PDFKit.PDFDocumentOptions;
    const doc: Doc;
    enum GuiaFields {
        nrAtendimento = "nrAtendimento",
        nrConta = "nrConta",
        numeroGuiaPrestador = "numeroGuiaPrestador",
        registroANS = "registroANS",
        numeroGuiaPrincipal = "numeroGuiaPrincipal",
        dataAutorizacao = "dataAutorizacao",
        senha = "senha",
        dataValidadeSenha = "dataValidadeSenha",
        numeroGuiaOperadora = "numeroGuiaOperadora",
        numeroCarteira = "numeroCarteira",
        validadeCarteira = "validadeCarteira",
        nomeBeneficiario = "nomeBeneficiario",
        cartaoNacionalSaude = "cartaoNacionalSaude",
        atendimentoRN = "atendimentoRN",
        'dadosSolicitante.codigoNaOperadora' = "dadosSolicitante.codigoNaOperadora",
        'dadosSolicitante.nomeContratado' = "dadosSolicitante.nomeContratado",
        'dadosSolicitante.nomeProfissionalSolicitante' = "dadosSolicitante.nomeProfissionalSolicitante",
        'dadosSolicitante.conselhoProfissional' = "dadosSolicitante.conselhoProfissional",
        'dadosSolicitante.numeroConselhoProfissional' = "dadosSolicitante.numeroConselhoProfissional",
        'dadosSolicitante.ufConselhoProfissional' = "dadosSolicitante.ufConselhoProfissional",
        'dadosSolicitante.codigoCBO' = "dadosSolicitante.codigoCBO",
        'dadosSolicitante.assinaturaProfissionalSoliciatante' = "dadosSolicitante.assinaturaProfissionalSoliciatante",
        'dadosSolicitacao.caraterAtendimento' = "dadosSolicitacao.caraterAtendimento",
        'dadosSolicitacao.dataSolicitacao' = "dadosSolicitacao.dataSolicitacao",
        'dadosSolicitacao.indicacaoClinica' = "dadosSolicitacao.indicacaoClinica",
        'dadosSolicitacao.procedimentosSolicitados' = "dadosSolicitacao.procedimentosSolicitados",
        'dadosExecutante.codigoNaOperadora' = "dadosExecutante.codigoNaOperadora",
        'dadosExecutante.nomeContratado' = "dadosExecutante.nomeContratado",
        'dadosExecutante.codigoCNES' = "dadosExecutante.codigoCNES",
        tipoAtendimento = "tipoAtendimento",
        indicacaoAcidente = "indicacaoAcidente",
        tipoConsulta = "tipoConsulta",
        motivoEncerramentoAtendimento = "motivoEncerramentoAtendimento",
        procedimentosRealizados = "procedimentosRealizados",
        profissionaisExecutantes = "profissionaisExecutantes",
        dataRealizacaoProcedimentos = "dataRealizacaoProcedimentos",
        observacaoJustificativa = "observacaoJustificativa",
        valorTotalProcedimentos = "valorTotalProcedimentos",
        valorTotalTaxasAlugueis = "valorTotalTaxasAlugueis",
        valorTotalMateriais = "valorTotalMateriais",
        valorTotalOPME = "valorTotalOPME",
        valorTotalMedicamentos = "valorTotalMedicamentos",
        valorTotalGasesMedicinais = "valorTotalGasesMedicinais",
        valorTotalGeral = "valorTotalGeral",
        assinaturaResponsavelAutorizacao = "assinaturaResponsavelAutorizacao",
        assinaturaBeneficiario = "assinaturaBeneficiario",
        assinaturaContratado = "assinaturaContratado"
    }
}
